# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: ror3deploy_development
  pool: 5
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  socket: /var/run/mysqld/mysqld.sock
  timeout: 5000

production:
  adapter: mysql2
  database: ror3deploy_development
  pool: 5
  username: root
  password: 
  timeout: 5000
  host: 127.0.0.1
  port: 3306
  socket: /var/run/mysqld/mysqld.sock
  timeout: 5000
